# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AdminBundle\Entity\Users: bcrypt

    providers:
        main:
            entity: { class: AdminBundle\Entity\Users, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /auth/login
                check_path: /login_check
                default_target_path: /admin/
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: ^/admin/.*, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }


